### ISSUE TITLE
Noting Issues with Route

### ISSUE THREAD

**Issue by AcriCAA** [PhillyOpen/Cycle-Philly-Android#1]
Right now when the app is tracking your route live, it does not plot your position, it is only after you have completed your ride that it plots your route.  However, there is a "note issue" feature that allows you to make notes about pavement issues, traffic issues etc.  The "note issue" function does not work after you complete a ride. 

It would be a nice if a user were able to drop pins on the route they just completed to note issues they encountered after the route and then have the app upload that data to the server.  

Kevin mentioned he could look into adding this functionality...

One killer feature would be if we could automatically link the "pavement issue" note to the Philly 311 system so that it would automatically upload a repair request to 311! See http://www.phila.gov/311/requestsubmission.html

**Comment by flibbertigibbet** [comment]
This issue was moved to CfABrigadePhiladelphia/Cycle-Philly-Android#6
