### ISSUE TITLE
trip lost when GPS unavailable at end

### ISSUE THREAD

**Issue by themightychris** [PhillyOpen/Cycle-Philly-Android#19]
I just recorded a trip and forgot to hit finish until a few minutes after I got inside. When I clicked finish, the error about no GPS signal being available popped up that often stops me from starting my trip indoors, but then it threw out my recorded trip and sent me back to the home screen even though the trip status screen had showed several miles recorded.

**Comment by flibbertigibbet** [comment]
This issue was moved to CfABrigadePhiladelphia/Cycle-Philly-Android#3
