### ISSUE TITLE
Feature: Ability to go into trips and add geo-tagged comments

### ISSUE THREAD

**Issue by emelleme** [PhillyOpen/Cycle-Philly-Android#7]
Feature: Ability to go into trips and add geo-tagged comments. these comments will be added in a separate table in the database to avoid conflict with the trip data

**Comment by flibbertigibbet** [comment]
This issue was moved to CfABrigadePhiladelphia/Cycle-Philly-Android#7

**Comment by flibbertigibbet** [comment]
This issue was moved to CfABrigadePhiladelphia/Cycle-Philly-Android#8
